sonar.projectKey=nmorab28_planify-monorepo
sonar.organization=nmorab28

sonar.projectName=planify-monorepo
sonar.sourceEncoding=UTF-8

# MONOREPO SOURCES
sonar.sources=frontend,backend 

# EXCLUSIONES
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/.next/**,**/coverage/**