sonar.projectKey=nmorab28_planify-monorepo
sonar.organization=nmorab28

sonar.projectName=planify-monorepo
sonar.sourceEncoding=UTF-8

# SOLO BACKEND
sonar.sources=backend/src

# EXCLUSIONES
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/.next/**,**/coverage/**

# DESACTIVAR COVERAGE TEMPORALMENTE
sonar.coverage.exclusions=**/*